version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: superblog
      MONGO_INITDB_ROOT_PASSWORD: superblog
      MONGO_INITDB_DATABASE: superblog
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017


